# Generated by Django 4.0.4 on 2022-05-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='welfare',
            name='welfare_condition',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='welfare',
            name='welfare_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
